version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - TOKEN_BOT=${TOKEN_BOT}
      - URL_API_SPOTIFY=${URL_API_SPOTIFY}
      - CODE_AUTORIZATON_SPOTIFY=${CODE_AUTORIZATON_SPOTIFY}
      - GET_TOKEN_SPOTIFY=${GET_TOKEN_SPOTIFY}
      - GENIUS_TOKEN=${GENIUS_TOKEN}
      - URL_GENIUS=${URL_GENIUS}
