name: bragi-ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Create ssh key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        shell: bash
        env:
          SSH_PRIVATE_KEY: "${{ secrets.SERVER_SSH_KEY }}"
      - name: Deploy
        run: |
          ssh -i "~/.ssh/id_rsa" ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}"
          cd ./bragi
          git pull
          yarn install
          pm2 restart bragi

        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          
        # uses: easingthemes/ssh-deploy@main
        # env:
        #   SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        #   ARGS: "-rltgoDzvO --delete"
        #   SOURCE: "src/"
        #   REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        #   REMOTE_USER: ${{ secrets.REMOTE_USER }}
        #   TARGET: ${{ secrets.REMOTE_TARGET }}