# name: bragi-ci
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     environment: production

#     steps:
#       - name: checkout
#         uses: actions/checkout@v1
#       - name: Create ssh key
#         run: |
#           install -m 600 -D /dev/null ~/.ssh/id_rsa
#           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#           ssh-keyscan -H ec2-177-71-145-235.sa-east-1.compute.amazonaws.com > ~/.ssh/known_hosts
#         shell: bash
#       - name: Deploy
#         run: |
#           ssh -tt -i ~/.ssh/id_rsa ubuntu@ec2-177-71-145-235.sa-east-1.compute.amazonaws.com
#           cd ~/bragi-bot
#           git pull
#           yarn install
#           pm2 restart bragi
#           exit
#         shell: bash
#         env:
#           remote_user: ${{ secrets.REMOTE_USER }}
#           remote_host: ${{ secrets.REMOTE_HOST }}